// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSUdCEJUakXpmX3kD5olz9px9I0A9CA_s',
    appId: '1:1027398974519:web:0e81e5295fedb5e57593b2',
    messagingSenderId: '1027398974519',
    projectId: 'qauth-47fd9',
    authDomain: 'qauth-47fd9.firebaseapp.com',
    storageBucket: 'qauth-47fd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEaN1WArv8g8LK6krAKMfFbERJ99qx1Y',
    appId: '1:1027398974519:android:6e0b0ebafc319fdf7593b2',
    messagingSenderId: '1027398974519',
    projectId: 'qauth-47fd9',
    storageBucket: 'qauth-47fd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqu2WsPqaF7i49Cv-p3wMqmrjQn8hL8XM',
    appId: '1:1027398974519:ios:d2837bf89c3ef1ed7593b2',
    messagingSenderId: '1027398974519',
    projectId: 'qauth-47fd9',
    storageBucket: 'qauth-47fd9.appspot.com',
    iosBundleId: 'top.loafman.qauth.qauth',
  );
}
