name: Basic Build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter doctor --verbose
      - run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: ls -R
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/ios/iphoneos/Runner.app.ipa