name: Basic Build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - name: Create env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      - run: ls
      - name: Fix env
        run: dart run build_runner build
      - run: flutter build apk --obfuscate --split-debug-info=./
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk
#  build-ios:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.19.4'
#          channel: 'stable'
#          cache: true
#      - run: flutter pub get
#      - run: flutter build ios --release --no-codesign
#      - name: Export ipa
#        run: xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release
#      - name: Upload IPA
#        uses: actions/upload-artifact@v4
#        with:
#          name: apk
#          path: build/ios/iphoneos/Runner.app.ipa
#  release:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: softprops/action-gh-release@v2